language: go
go:
- 1.11
install:
- make install
script:
- make build_for_local
deploy:
  provider: heroku
  api_key:
    secure: GO2XTLi/Jz1v7oUWSr8gSUfXFRIo1BqW8uUvZYxgOBDZBE58PldavYohKvTEITayu01PxuVKARDSAacZgV9Zwa5zSKEkDQbDbMOCy5MJLG/avod0ua/zgxMAO11aOo4liT1fR+nbXDnhDgZhaYZTXMM4l8Jr+s5kp+u+JBxrT213YfL/FNJxriUY0do4J872q8ybgIIjY+YMOki9w5yQQji79N0u+fpDmUJc6Ike1YaPCBM44695R3hYCQGvOVF3Ty8xJQVGVc7rIgtgCwESOzKl25f5PKEX9wlVjwUDXVEK+MpgVmbt7Gsn2QdBTC9fJnKYfv4QTA1+ss+/6EvzoaHXnqsVV6nQYFmaADtT+dynP4XEGdkzJ4BwjcdU/VIYHG2gRcirfvmR2CHemoqgSiqSX2f6JTjd7fzgl/4oe+Ze0aws5ij4c3r3KsUIwLWSvh8ZIu+QLmzAsvMV7kRgkg+G/8AVGV3x8bRdu8jCrabCJc9J8k47iH41N5FWTcIpoWjbK06182jYM4sHMou3FP/e/Af1UK64DozwQJx9sJTL6dUwOVHyTwokbGchRZjNNrvn60XbJ7hy+NyxSmFBl4kNcFiG/z/l91T3jvOqhB9+VeDppAjDt9VxUq25sqLNOnedjaJb5IiUI8FC+04j1SWk5bVzZeaRqroq7RFu2wg=
  app: reviewer-notification
  on:
    repo: ara-ta3/reviewer-notification
notifications:
  slack:
    secure: RSXLjeliQF/ooOlq2Qm4Hd+hBIR5DyHsGfNthhSQA7zKCgMwb99RdB95tH6hgUBUuqKCC6us4V/yILMo+UccLSI+xSDMYaBdQo1dX8Rez3SWFjTEfX6fre65zA5dj7qCisCbRyR/p5U7uFW31HCra209EKGvEj87iEuWM+qjHLJXdrIUsA77LxSscFRRBrciKBMQ/9XmJpJi9d0XPxA2DOdt07Sh3xA6zwWJ++fBE7JDh33cmDoAP7jfoI3A0rLE9xO6KHQNgHk76ux/N6HlNW2qXiJwqBnLItvj4RFdF+8SV3tUOPXIQq9TSNARfETlBfHP2cTZl0MoJ2BFCbZqU5wmWaplZbVqVo0q56akZSCPInheulOCW9jCQxvoaOwLANdvrWPDcrqWpUFwO9CYXuL1H0vjGu/F+sqjTAPKd0A7+PWwQx+n+i6vQPpPWA8VPq3RJgQwTILCjwFGk1hXVnAkmU4Q6/un5qu+5W58S8Sg1q/ojo+SlzQmba7xyR56/b+x1fJOua2B/5UC81rZrXZmHhq3l4/eNJkM5ZYLTuKecLnbP8n5rCVkZ8HkMIeg0ojaAxsVSd+F+3LxZN6PL6OFQYSP1ATCVayubq+csspexDmr+ZXtrT5VSVUpB+ZyYNe3iitduXFAsRxLPn9bY4h9dzm9n4SsrulzdrhGNtE=
